import type { Metadata } from "next";
import { DM_Sans, JetBrains_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "@/components/providers";
import { ServiceWorkerRegister } from "@/components/sw-register";
import { Toaster } from "sonner";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["400", "600"],
});

import type { Viewport } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://github.com/luna-prompts/skillnote"),
  title: {
    default: "SkillNote",
    template: "%s · SkillNote",
  },
  description: "Self-hosted skill registry for AI coding agents.",
  applicationName: "SkillNote",
  appleWebApp: {
    capable: true,
    title: "SkillNote",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "SkillNote",
    description:
      "Self-hosted skill registry for AI coding agents. Write SKILL.md once, ship to Claude Code / OpenClaw / Cursor.",
    type: "website",
    siteName: "SkillNote",
  },
  twitter: {
    card: "summary",
    title: "SkillNote",
    description: "Self-hosted skill registry for AI coding agents.",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: "#0d9488",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* All other PWA meta is generated by Next.js from the metadata + viewport
            exports above (theme-color, apple-mobile-web-app-*, manifest link, etc.).
            apple-touch-icon is the one that still needs an explicit <link> because
            Next's metadata API requires it in the `icons.apple` field rather than
            auto-detecting public/apple-touch-icon.png. */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
      </head>
      <body
        className={`${dmSans.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster position="bottom-right" richColors />
          <ServiceWorkerRegister />
        </Providers>
      </body>
    </html>
  );
}
