import type { Metadata } from "next";
import { DM_Sans, JetBrains_Mono } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Providers } from "@/components/providers";
import { ServiceWorkerRegister } from "@/components/sw-register";
import { Toaster } from "sonner";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "600", "700"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  weight: ["400", "600"],
});

import type { Viewport } from "next";

export const metadata: Metadata = {
  metadataBase: new URL("https://github.com/luna-prompts/skillnote"),
  title: {
    default: "SkillNote",
    template: "%s · SkillNote",
  },
  description: "Self-hosted skill registry for AI coding agents.",
  applicationName: "SkillNote",
  appleWebApp: {
    capable: true,
    title: "SkillNote",
    statusBarStyle: "black-translucent",
  },
  openGraph: {
    title: "SkillNote",
    description:
      "Self-hosted skill registry for AI coding agents. Write SKILL.md once, ship to Claude Code / OpenClaw / Cursor.",
    type: "website",
    siteName: "SkillNote",
  },
  twitter: {
    card: "summary",
    title: "SkillNote",
    description: "Self-hosted skill registry for AI coding agents.",
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  // R9: match `src/app/manifest.ts` — drop the teal brand accent from the
  // standalone-app chrome. Pure black so the titlebar + dock-icon frame
  // match the icon's own black background.
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* All other PWA meta is generated by Next.js from the metadata + viewport
            exports above (theme-color, apple-mobile-web-app-*, manifest link, etc.).
            apple-touch-icon is the one that still needs an explicit <link> because
            Next's metadata API requires it in the `icons.apple` field rather than
            auto-detecting public/apple-touch-icon.png. */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        {/* R9 F40: pre-React, synchronous capture of the `?api=<URL>` query
            param. Without this, the FIRST API fetch fires before
            <ApiUrlBootstrap /> mounts → it uses the build-time default
            (`http://localhost:8082`) → connection refused → "Backend
            unreachable" flash. Running this in <head> guarantees the
            override lands in localStorage before any client code reads
            `skillnote:api-url`. The component still cleans up the URL
            param + re-validates after hydration. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
(function () {
  try {
    var u = new URL(location.href);
    var raw = u.searchParams.get('api');
    if (!raw) return;
    var c;
    try { c = new URL(raw); } catch (e) { return; }
    if (c.protocol !== 'http:' && c.protocol !== 'https:') return;
    var sameHost = c.hostname === 'localhost' || c.hostname === '127.0.0.1' || c.hostname === location.hostname;
    if (!sameHost) return;
    try { localStorage.setItem('skillnote:api-url', c.origin); } catch (e) {}
  } catch (e) {}
})();
            `.trim(),
          }}
        />
      </head>
      <body
        className={`${dmSans.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <Providers>
          <TooltipProvider>{children}</TooltipProvider>
          <Toaster position="bottom-right" richColors />
          <ServiceWorkerRegister />
        </Providers>
      </body>
    </html>
  );
}
