#!/usr/bin/env bash
#
# release-tap.sh — publish the SkillNote Homebrew formula to luna-prompts/homebrew-tap.
#
# Usage:
#   ./scripts/release-tap.sh                 # uses version from package.json
#   ./scripts/release-tap.sh 0.5.3           # explicit version override
#
# This is the manual fallback for the auto-update CI workflow at
# .github/workflows/homebrew-tap.yml. It also handles the initial seed:
# the first time it runs against an empty homebrew-tap repo, it creates
# the Formula/ directory and adds the formula.
#
# Required:
#   - gh CLI authenticated as someone with push to luna-prompts/homebrew-tap
#   - curl, shasum, sed
#
# What this does:
#   1. Reads the target version (arg or package.json)
#   2. Downloads the npm tarball and computes its sha256
#   3. Clones (or pulls) the homebrew-tap repo into a temp dir
#   4. Writes Formula/skillnote.rb with the new version + sha256
#   5. Commits and pushes
#
# Idempotent: re-running against a tap that already has this version is
# a no-op (the diff will be empty and `git commit` will fail cleanly).

set -euo pipefail

REPO_OWNER="luna-prompts"
TAP_REPO="homebrew-tap"
FORMULA_NAME="skillnote"

VERSION="${1:-}"
if [[ -z "$VERSION" ]]; then
  VERSION=$(node -p "require('$(git rev-parse --show-toplevel)/package.json').version")
fi
echo "==> Releasing formula for skillnote@${VERSION}"

# Step 1: download tarball + compute sha256
TARBALL_URL="https://registry.npmjs.org/${FORMULA_NAME}/-/${FORMULA_NAME}-${VERSION}.tgz"
TMP_TARBALL=$(mktemp -t skillnote-tarball.XXXXXX.tgz)
trap 'rm -f "$TMP_TARBALL"' EXIT

echo "==> Downloading $TARBALL_URL"
curl -fsSL "$TARBALL_URL" -o "$TMP_TARBALL"
SHA256=$(shasum -a 256 "$TMP_TARBALL" | awk '{print $1}')
echo "==> sha256: $SHA256"

# Step 2: clone (or refresh) the tap repo
TAP_DIR=$(mktemp -d -t homebrew-tap.XXXXXX)
trap 'rm -rf "$TAP_DIR"; rm -f "$TMP_TARBALL"' EXIT

echo "==> Cloning ${REPO_OWNER}/${TAP_REPO}"
gh repo clone "${REPO_OWNER}/${TAP_REPO}" "$TAP_DIR" -- --depth=1

# Step 3: write the formula
mkdir -p "$TAP_DIR/Formula"
cat > "$TAP_DIR/Formula/${FORMULA_NAME}.rb" <<EOF
# typed: false
# frozen_string_literal: true

# Auto-generated by scripts/release-tap.sh in luna-prompts/skillnote.
# Do not edit by hand — changes will be overwritten on the next release.
class Skillnote < Formula
  desc "Self-hosted skill registry for AI coding agents"
  homepage "https://github.com/luna-prompts/skillnote"
  url "${TARBALL_URL}"
  sha256 "${SHA256}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/skillnote --version")
  end
end
EOF

# Step 4: commit + push if anything changed
cd "$TAP_DIR"
if [[ -z "$(git status --porcelain)" ]]; then
  echo "==> Formula already up-to-date at version ${VERSION}. Nothing to push."
  exit 0
fi

git add "Formula/${FORMULA_NAME}.rb"
git commit -m "skillnote ${VERSION}

Published from luna-prompts/skillnote via scripts/release-tap.sh.
Tarball: ${TARBALL_URL}
sha256:  ${SHA256}"

echo "==> Pushing to ${REPO_OWNER}/${TAP_REPO}"
git push

echo "==> Done. Install with: brew install ${REPO_OWNER}/tap/${FORMULA_NAME}"
